import contacts from "./modules/contacts";
import menu from "./modules/menu";
import scroll from "./modules/scroll";
import modalRepair from "./modules/modalRepair";
import maskPhone from "./modules/maskPhone";
import modalPrivacy from "./modules/modalPrivacy";
import modalConsult from "./modules/modalConsult";
import sendForm from "./modules/sendForm";
import tips from "./modules/tips";
import modalPortfolio from "./modules/modalPortfolio";
import sliderPortfolio from "./modules/sliderPortfolio";
import modalDocuments from "./modules/modalDocuments";
import sliderDocuments from "./modules/sliderDocuments";
import sliderRepairTypes from "./modules/sliderRepairTypes";
import sliderReviews from "./modules/sliderReviews";
import sliderServices from "./modules/sliderServices";
import sliderFormula from "./modules/sliderFormula";
import accordionFaq from "./modules/accordionFaq";

contacts();
menu();
scroll();
modalRepair();
maskPhone();
modalPrivacy();
modalConsult();
sendForm();
tips();
modalPortfolio();
sliderPortfolio();
modalDocuments();
sliderDocuments();
sliderRepairTypes();
sliderReviews();
sliderServices();
sliderFormula();
accordionFaq();